# Generated by Django 2.1.2 on 2018-10-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_one_first_name', models.CharField(max_length=50)),
                ('person_one_last_name', models.CharField(max_length=50)),
                ('person_two_first_name', models.CharField(max_length=50)),
                ('person_two_last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('queries', models.IntegerField()),
                ('match_id', models.CharField(max_length=50)),
            ],
        ),
    ]
