# Generated by Django 2.1.2 on 2018-10-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='match_id',
            field=models.IntegerField(),
        ),
    ]
