# Generated by Django 2.1.2 on 2018-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0002_auto_20181005_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='queries',
            field=models.IntegerField(default=0),
        ),
    ]
