# Generated by Django 2.1.2 on 2018-10-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0003_auto_20181005_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='person_two_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='person_two_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
