# Generated by Django 2.1.2 on 2018-10-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0004_auto_20181005_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
