# Generated by Django 2.1.2 on 2018-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0005_auto_20181005_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.TextField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
