# Generated by Django 2.1.2 on 2018-10-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0007_auto_20181007_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
