# Generated by Django 2.1.2 on 2018-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0008_remove_participant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='query_limit',
            field=models.IntegerField(default=5),
        ),
    ]
