# Generated by Django 2.1.2 on 2018-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchups', '0009_participant_query_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='found_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='found_match_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
